#!/usr/bin/env python3
"""Generate dataref declarations and tables from the frozen thesis evidence.

No measurements run here. evidence/current is a byte-for-byte export of
thesis/evidence at the revision recorded in evidence/origin.json.
"""
from pathlib import Path
import csv, hashlib, json, re
ROOT = Path(__file__).resolve().parent
DATA = ROOT / 'evidence/current'
values = {}
lines = ['% Generated by prepare_data.py; edit evidence inputs, not this file.']
def rows(name, old=False):
    p = ROOT / ('evidence/previous' if old else 'evidence/current') / name
    lines.append('% Source: '+str(p.relative_to(ROOT))+' SHA-256 '+hashlib.sha256(p.read_bytes()).hexdigest())
    return list(csv.DictReader(p.open()))
def put(key, value):
    value = str(value)
    assert key not in values, key
    values[key] = value
    lines.append('\\drefset{/'+key+'}{'+value+'}')
def numeric(prefix, row):
    for k,v in row.items():
        v=v.strip().replace('×','')
        if re.fullmatch(r'[+-]?\d+(?:\.\d+)?',v): put(prefix+'/'+k.lower().replace('_','-'),v)
def d(k): return '\\dref{/'+k+'}'
cat = rows('catalogue.csv')
put('catalogue/total',len(cat));put('catalogue/real',sum(r['kind']=='real' for r in cat))
put('catalogue/control',sum(r['kind'].startswith('control') for r in cat))
put('catalogue/synthetic',sum(r['kind']=='synthetic' for r in cat))
put('catalogue/covered',len(cat)-1)
for name in ['totals','classes','measured','crosscheck','control','nonmonotone']:
    for i,r in enumerate(rows('tier1-'+name+'.csv')): numeric('tier1/'+name+'/'+r.get('n',str(i)),r)
fit={}
for old in [False,True]:
    tag='previous' if old else 'current'
    for r in rows('tier2-fit.csv',old):
        q={'total (compose only)':'compose'}.get(r['quantity'],r['quantity'])
        numeric('tier2/'+tag+'/'+q,r);fit[tag+'/'+q]=r
for r in rows('tier2-by-n.csv'):
    numeric('timing/'+r['n'],r)
    for k in ['packages','alt_groups','debconf_records']:
        vs=r[k].split('–');put('timing/'+r['n']+'/'+k.replace('_','-')+'-min',vs[0]);put('timing/'+r['n']+'/'+k.replace('_','-')+'-max',vs[-1])
for r in rows('tier2-checks.csv'): numeric('checks/'+r['check'],r)
cohorts=rows('storage-cohorts.csv')
for r in cohorts:
    name={'small adversarial':'small','large realistic':'large','whole catalogue':'all'}[r['cohort']]
    numeric('storage/'+name,r)
mods=rows('storage-per-module.csv')
for r in mods:numeric('module/'+r['module'],r)
for r in rows('storage-model-check.csv'):numeric('calibration/'+r['module'],r)
for i,r in enumerate(rows('storage-sensitivity.csv')):numeric('sensitivity/'+str(i),r)
# The exact base size is recorded in the permitted artefact inventory.
for r in csv.DictReader((DATA/'provenance-artefacts.csv').open()):
    if 'base' in [r.get('artefact'),r.get('module'),r.get('name')]:
        put('storage/base-mb',round(int(r['bytes'])/1000000,1));break
else:
    text=(DATA/'storage.md').read_text()
    assert '41.7' in text
    put('storage/base-mb','41.7')
boot=rows('tier3.csv'); completed=[r for r in boot if r['verdict'] in ('PASS','FAIL')]
put('boot/bundles',len(boot));put('boot/current',sum('superseded' not in r['note'] for r in boot))
for verdict in ['PASS','FAIL','BROKEN','ABORTED','no result']:put('boot/'+verdict.replace(' ','-').lower(),sum((r['verdict'] or 'no result')==verdict for r in boot))
for i,r in enumerate(boot):numeric('boot/run/'+str(i),r)
put('boot/completed',len(completed));put('boot/min-s',min(int(r['duration_s']) for r in completed));put('boot/max-s',max(int(r['duration_s']) for r in completed))
a=float(fit['current/compose']['intercept_ms'])+float(fit['current/verify']['intercept_ms'])
b=float(fit['current/compose']['slope_ms_per_module'])+float(fit['current/verify']['slope_ms_per_module'])
put('tier2/combined/intercept-ms',f'{a:.1f}');put('tier2/combined/slope-ms',f'{b:.2f}')
old=fit['previous/compose'];new=fit['current/compose']
put('comparison/slope-change-pct',f"{100*abs(float(new['slope_ms_per_module'])/float(old['slope_ms_per_module'])-1):.2f}")
put('comparison/intercept-change-pct',f"{100*(1-float(new['intercept_ms'])/float(old['intercept_ms'])):.1f}")
for n in [2,36]:
    bs=[int(r['duration_s'])*1000/(a+b*n) for r in completed if int(r['n'])==n]
    put(f'gap/{n}/min',round(min(bs)));put(f'gap/{n}/max',round(max(bs)))
# Historical derived model, traced in claims.md (not a current experiment).
claims=(DATA/'claims.md').read_text()
for token in ['1 023.8','777.2','113.5','69.6','38-module']:assert token in claims
for key,val in [('n',38),('thin',1023.8),('fat',777.2),('base-increment',113.5),('best-delta-saving',69.6)]:put('fatbase/'+key,val)
put('fatbase/reduction-pct',f'{100*(1-777.2/1023.8):.1f}')
(ROOT/'data.tex').write_text('\n'.join(lines)+'\n')
# Complete per-module inventory is supplementary, keeping the main analysis readable.
out=[r'\begin{longtable}{lrrr}',r'\caption{Compressed module inventory for the \dref{/catalogue/total}-module catalogue. Marginal saving assumes the base is already stored.}\label{tab:module-inventory}\\',r'\toprule Module & Delta (\si{\mega\byte}) & Model (\si{\mega\byte}) & Saving (\si{\percent}) \\',r'\midrule\endfirsthead',r'\toprule Module & Delta (\si{\mega\byte}) & Model (\si{\mega\byte}) & Saving (\si{\percent}) \\',r'\midrule\endhead']
for r in mods:
    k='module/'+r['module'];out.append(r['module']+' & '+d(k+'/delta-mb')+' & '+d(k+'/monolithic-mb')+' & '+d(k+'/saving-pct')+r' \\')
out += [r'\bottomrule\end{longtable}']
(ROOT/'tables-modules.tex').write_text('\n'.join(out)+'\n')
print(f'Generated {len(values)} dataref declarations from frozen evidence.')

def write(name, parts):
    (ROOT/name).write_text('\n'.join(parts)+'\n')
def dv(key): return r'\drefvalueof{/'+key+'}'
# All table cells and plot points reference the same dataref declarations.
timing=list(csv.DictReader((DATA/'tier2-by-n.csv').open()))
out=[r'\begin{table}[tbp]\centering\small',r'\begin{tabular}{rrrrrrr}',r'\toprule $N$ & Samples & Packages & Mount & Reconcile & Compose & Verify \\',r'\midrule']
for r in timing:
    k='timing/'+r['n']
    out.append(' & '.join([d(k+'/n'),d(k+'/samples'),r'\numrange{'+dv(k+'/packages-min')+'}{'+dv(k+'/packages-max')+'}']+[d(k+'/'+f+'-ms-mean') for f in ['mount','reconcile','total','verify']])+r' \\')
out += [r'\bottomrule\end{tabular}',r'\caption{Physical sample from the \dref{/catalogue/total}-module catalogue; \dref{/catalogue/covered} distinct ordinary deltas are covered. $N$ excludes base. Durations are mean milliseconds; package columns give observed ranges.}\label{tab:physical}',r'\end{table}']
write('tables-timing.tex',out)
out=[r'\begin{figure}[tbp]\centering',r'\begin{tikzpicture}',r'\begin{axis}[width=.94\textwidth,height=6.7cm,xlabel={Sibling deltas $N$ (base excluded)},ylabel={Duration (\si{\milli\second})},xmin=0,xmax=40,ymin=0,grid=major,legend pos=north west,legend style={font=\small}]']
for phase,col,color,mark in [('compose','total','blue','*'),('verify','verify','orange','square*')]:
    coords=' '.join('('+dv('timing/'+r['n']+'/n')+','+dv('timing/'+r['n']+'/'+col+'-ms-mean')+')' for r in timing)
    out += [r'\addplot[only marks,'+color+',mark='+mark+'] coordinates {'+coords+'};',r'\addlegendentry{'+phase.capitalize()+' mean}',r'\addplot['+color+',domain=2:38,no marks,dashed] {'+dv('tier2/current/'+phase+'/intercept-ms')+'+'+dv('tier2/current/'+phase+'/slope-ms-per-module')+'*x};',r'\addlegendentry{'+phase.capitalize()+' fit}']
out += [r'\end{axis}\end{tikzpicture}',r'\caption{Physical phase means and fits for the \dref{/catalogue/total}-module catalogue (\dref{/catalogue/covered} ordinary deltas covered). Sample counts appear in \cref{tab:physical}; the fit uses all \dref{/tier2/current/compose/n} rows. Aggregate summaries supply no dispersion estimates, so no uncertainty band is inferred. Plot preparation assisted by H1.}\label{fig:timing}',r'\end{figure}']
write('figures-timing.tex',out)
out=[r'\begin{figure}[tbp]\centering',r'\begin{tikzpicture}',r'\begin{axis}[ybar,bar width=15pt,width=.94\textwidth,height=6cm,ymin=0,ymax=4200,ylabel={Compressed size (\si{\mega\byte})},symbolic x coords={Small,Large,All},xtick=data,legend pos=north west,legend style={font=\small},scaled y ticks=false,ymajorgrids]']
for col,color,label in [('stored-mb','blue','Stored base and deltas'),('monolithic-mb','orange','Modelled monoliths')]:
    out += [r'\addplot[fill='+color+'!50,draw='+color+'] coordinates {'+' '.join('('+name+','+dv('storage/'+k+'/'+col)+')' for name,k in [('Small','small'),('Large','large'),('All','all')])+'};',r'\addlegendentry{'+label+'}']
out += [r'\end{axis}\end{tikzpicture}',r'\caption{Storage comparison for the \dref{/catalogue/total}-module catalogue: \dref{/storage/small/n} small and \dref{/storage/large/n} large modules. Each cohort counts the base once in modular storage; cohort bars therefore must not be summed. Plot preparation assisted by H1.}\label{fig:storage}',r'\end{figure}']
write('figures-storage.tex',out)
out=[r'\begin{table}[tbp]\centering\small',r'\begin{tabular}{lrrr}',r'\toprule Module & Measured (\si{\mega\byte}) & Model (\si{\mega\byte}) & Error (\si{\percent}) \\',r'\midrule']
for r in csv.DictReader((DATA/'storage-model-check.csv').open()):
    k='calibration/'+r['module'];out.append(r['module']+' & '+' & '.join(d(k+'/'+f) for f in ['measured-mb','modelled-mb','model-error-pct'])+r' \\')
out += [r'\bottomrule\end{tabular}',r'\caption{Independent monolithic calibration within the \dref{/catalogue/total}-module catalogue. Positive error means the additive model exceeds the measured monolith size.}\label{tab:calibration}',r'\end{table}']
write('tables-calibration.tex',out)
out=[r'\begin{table}[tbp]\centering\small',r'\begin{tabularx}{\textwidth}{@{}Ylrl@{}}',r'\toprule Selected modules / order & Verdict & Time (\si{\second}) & Key observation \\',r'\midrule']
for i,name,note in [(11,'nginx alone','nginx listener'),(14,'Apache alone','Apache listener'),(15,'nginx, Apache','Apache failed'),(16,'Apache, nginx','Apache failed'),(0,'MySQL, PostgreSQL','Both listeners'),(4,'PostgreSQL, MySQL','Both listeners'),(19,'Large selected set','Apache failed'),(8,'Driver, CUDA runtime','No GPU access')]:
    r=boot[i];out.append(name+' & '+r['verdict']+' & '+d('boot/run/'+str(i)+'/duration-s')+' & '+note+r' \\')
out += [r'\bottomrule\end{tabularx}',r'\caption{Selected boot observations from the retained history, not a current exhaustive \dref{/catalogue/total}-module boot census. The large selected set has \dref{/boot/run/19/n} deltas. Only the displayed GPU pair remains non-superseded; its probes do not test hardware operation.}\label{tab:boots}',r'\end{table}']
write('tables-boots.tex',out)
