#!/usr/bin/env python3
"""Reconcile the registry files that every module rewrites (conflict class 5).

    reconcile.py --merged DIR [--groups-out FILE] NAME=LAYERDIR [NAME=LAYERDIR ...]

Layers are given in STACKING ORDER, lowest first, so later layers win -- the
same order the overlay itself uses. Layers are directories: normally the
read-only mount points of the .sqsh artefacts, so reconciliation depends on
artefacts alone and never on a build tree.

Five registries diverge when modules are stacked. Four are merged here; the
fifth is regenerated by its own tool, which the caller runs afterwards:

  /var/lib/dpkg/status            union, later layer wins        (here)
  /var/lib/dpkg/alternatives/*    union of candidate lists       (here)
  /var/lib/dpkg/diversions        union                          (here)
  /var/lib/apt/extended_states    union                          (here)
  /etc/alternatives/*             REGENERATED by update-alternatives --auto
  /etc/ld.so.cache                REGENERATED by ldconfig

The two regenerated ones are deliberately not reimplemented. /etc/alternatives
symlinks are owned by no package, so there is nothing to merge -- they are a
FUNCTION of the merged registry and its priorities, and update-alternatives is
the authority on computing them. Same argument for ldconfig.

Exit: 0 reconciled, 2 something was unreadable or inconsistent.
"""
import json, os, sys

# ---------------------------------------------------------------- helpers
def read(path):
    try:
        with open(path, encoding='utf-8', errors='replace') as f:
            return f.read()
    except FileNotFoundError:
        return None
    except OSError as exc:
        sys.stderr.write("cannot read %s: %s\n" % (path, exc)); sys.exit(2)

def write(path, text):
    # dirname('') is '' and makedirs('') raises; a bare filename is legitimate.
    os.makedirs(os.path.dirname(path) or '.', exist_ok=True)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(text)

def stanzas(text):
    return [s for s in (text or '').split('\n\n') if s.strip()]

def field(stanza, key):
    for line in stanza.split('\n'):
        if line.startswith(key + ': '):
            return line[len(key) + 2:]
    return None

# ---------------------------------------------------------------- dpkg status
def merge_status(layers, merged):
    keep, order, diverged = {}, [], []
    for name, root in layers:
        for s in stanzas(read(os.path.join(root, 'var/lib/dpkg/status'))):
            pkg = field(s, 'Package')
            if not pkg: continue
            st = (field(s, 'Status') or '').split()
            if len(st) != 3 or st[2] != 'installed':
                continue
            ver = field(s, 'Version')
            if pkg in keep:
                if keep[pkg][0] != ver:
                    diverged.append((pkg, keep[pkg][1], keep[pkg][0], name, ver))
                keep[pkg] = (ver, name, s)
            else:
                keep[pkg] = (ver, name, s); order.append(pkg)
    write(os.path.join(merged, 'var/lib/dpkg/status'),
          '\n\n'.join(keep[p][2] for p in order) + '\n')
    return len(order), diverged

# ---------------------------------------------------------------- alternatives
# Format of /var/lib/dpkg/alternatives/<group>:
#     <status>            auto | manual
#     <link>              e.g. /usr/bin/editor
#     <slave name> / <slave link>   repeating pairs
#     <blank>             ends the slave list
#     then, packed with NO separator, one record per candidate:
#     <path> / <priority> / exactly one line per slave, EMPTY when that
#     candidate provides no such slave
#     <blank>             ends the file
def parse_alt(text):
    L = text.split('\n')
    if len(L) < 2: raise ValueError('truncated alternatives file')
    status, link, i = L[0], L[1], 2
    slaves = []
    while i < len(L) and L[i] != '':
        slaves.append((L[i], L[i + 1] if i + 1 < len(L) else ''))
        i += 2
    i += 1
    alts = []
    while i < len(L) and L[i] != '':
        path, prio, i = L[i], L[i + 1] if i + 1 < len(L) else '0', i + 2
        paths = L[i:i + len(slaves)]
        paths += [''] * (len(slaves) - len(paths))
        i += len(slaves)
        alts.append((path, prio, dict(zip([s for s, _ in slaves], paths))))
    return status, link, slaves, alts

def render_alt(status, link, slaves, alts):
    out = [status, link]
    for sname, slink in slaves:
        out += [sname, slink]
    out.append('')
    for path, prio, smap in alts:
        out += [path, prio]
        out += [smap.get(sname, '') for sname, _ in slaves]
    out.append('')
    return '\n'.join(out) + '\n'

def merge_alternatives(layers, merged):
    groups, problems = {}, []
    for name, root in layers:
        d = os.path.join(root, 'var/lib/dpkg/alternatives')
        if not os.path.isdir(d): continue
        for g in sorted(os.listdir(d)):
            text = read(os.path.join(d, g))
            if text is None: continue
            try:
                status, link, slaves, alts = parse_alt(text)
            except Exception as exc:
                problems.append("%s/%s: %s" % (name, g, exc)); continue
            e = groups.setdefault(g, {'status': [], 'link': None,
                                      'slaves': [], 'alts': {}, 'from': []})
            e['status'].append(status)
            if e['link'] is None:
                e['link'] = link
            elif e['link'] != link:
                problems.append("%s: link differs (%s vs %s)" % (g, e['link'], link))
            have = {s for s, _ in e['slaves']}
            for sname, slink in slaves:
                if sname not in have:
                    e['slaves'].append((sname, slink)); have.add(sname)
            for path, prio, smap in alts:
                e['alts'][path] = (prio, smap)      # later layer wins
            if name not in e['from']: e['from'].append(name)

    for g, e in groups.items():
        # A composed image has no operator who chose an alternative, and the
        # symlinks are about to be recomputed by priority anyway, so 'manual'
        # is only preserved when every layer agreed on it.
        status = e['status'][0] if len(set(e['status'])) == 1 else 'auto'
        alts = sorted(e['alts'].items(),
                      key=lambda kv: (-int(kv[1][0] or 0), kv[0]))
        rendered = [(p, pr, sm) for p, (pr, sm) in alts]
        write(os.path.join(merged, 'var/lib/dpkg/alternatives', g),
              render_alt(status, e['link'], e['slaves'], rendered))
    return groups, problems

# ---------------------------------------------------------------- diversions
# Flat file, three lines per record: original path, diverted-to path, package.
def merge_diversions(layers, merged):
    seen, out = set(), []
    for name, root in layers:
        text = read(os.path.join(root, 'var/lib/dpkg/diversions'))
        if not text: continue
        L = [l for l in text.split('\n') if l != '']
        for i in range(0, len(L) - 2, 3):
            rec = (L[i], L[i + 1], L[i + 2])
            if rec in seen: continue
            seen.add(rec); out.append(rec)
    if out:
        write(os.path.join(merged, 'var/lib/dpkg/diversions'),
              ''.join('%s\n%s\n%s\n' % r for r in out))
    return len(out)

# ---------------------------------------------------------------- extended_states
def merge_extended_states(layers, merged):
    keep, order = {}, []
    for name, root in layers:
        for s in stanzas(read(os.path.join(root, 'var/lib/apt/extended_states'))):
            key = (field(s, 'Package'), field(s, 'Architecture'))
            if key[0] is None: continue
            if key not in keep: order.append(key)
            keep[key] = s
    if order:
        write(os.path.join(merged, 'var/lib/apt/extended_states'),
              '\n\n'.join(keep[k] for k in order) + '\n')
    return len(order)

# ---------------------------------------------------------------- main
def main(argv):
    merged, groups_out, layers = None, None, []
    i = 0
    while i < len(argv):
        a = argv[i]
        if a == '--merged':      merged = argv[i + 1]; i += 2
        elif a == '--groups-out': groups_out = argv[i + 1]; i += 2
        elif '=' in a:            n, _, d = a.partition('='); layers.append((n, d)); i += 1
        else:
            sys.stderr.write("unexpected argument: %s\n" % a); return 2
    if not merged or not layers:
        sys.stderr.write(__doc__); return 2
    for n, d in layers:
        if not os.path.isdir(d):
            sys.stderr.write("layer %s: not a directory: %s\n" % (n, d)); return 2

    npkg, diverged = merge_status(layers, merged)
    print("  dpkg status        : %d packages" % npkg)
    if diverged:
        print("  version divergence : %d" % len(diverged))
        for p, m1, v1, m2, v2 in diverged[:10]:
            print("      %-28s %s=%s -> %s=%s" % (p, m1, v1, m2, v2))
    else:
        print("  version divergence : none")

    groups, problems = merge_alternatives(layers, merged)
    print("  alternatives       : %d link group(s)" % len(groups))
    for g in sorted(groups):
        e = groups[g]
        if len(e['from']) > 1 or len(e['alts']) > 1:
            cands = sorted(((int(pr or 0), p) for p, (pr, _) in e['alts'].items()),
                           reverse=True)
            print("      %-12s %d candidate(s) from %s: %s"
                  % (g, len(cands), '+'.join(e['from']),
                     ', '.join("%s(%d)" % (os.path.basename(p), pr) for pr, p in cands)))
    for pr in problems:
        print("      PROBLEM %s" % pr)

    print("  diversions         : %d" % merge_diversions(layers, merged))
    print("  extended_states    : %d" % merge_extended_states(layers, merged))

    if groups_out:
        write(groups_out, ''.join(g + '\n' for g in sorted(groups)))
    return 2 if problems else 0

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
