#!/usr/bin/env python3
"""Reconcile the registry files that every module rewrites (conflict class 5).

    reconcile.py --merged DIR [--groups-out FILE] NAME=LAYERDIR [NAME=LAYERDIR ...]

Layers are given in STACKING ORDER, lowest first, so later layers win -- the
same order the overlay itself uses. Layers are directories: normally the
read-only mount points of the .sqsh artefacts, so reconciliation depends on
artefacts alone and never on a build tree.

Five registries diverge when modules are stacked. Four are merged here; the
fifth is regenerated by its own tool, which the caller runs afterwards:

  /etc/passwd, group, shadow,     union by record, member lists
  gshadow, subuid, subgid         merged                         (here)
  /var/lib/dpkg/status            union, later layer wins        (here)
  /var/lib/dpkg/alternatives/*    union of candidate lists       (here)
  /var/lib/dpkg/diversions        union                          (here)
  /var/lib/apt/extended_states    union                          (here)
  /etc/alternatives/*             REGENERATED by update-alternatives --auto
  /etc/ld.so.cache                REGENERATED by ldconfig

The two regenerated ones are deliberately not reimplemented. /etc/alternatives
symlinks are owned by no package, so there is nothing to merge -- they are a
FUNCTION of the merged registry and its priorities, and update-alternatives is
the authority on computing them. Same argument for ldconfig.

Exit: 0 reconciled, 2 something was unreadable or inconsistent.
"""
import json, os, stat, sys

# ---------------------------------------------------------------- helpers
def read(path):
    try:
        with open(path, encoding='utf-8', errors='replace') as f:
            return f.read()
    except FileNotFoundError:
        return None
    except OSError as exc:
        sys.stderr.write("cannot read %s: %s\n" % (path, exc)); sys.exit(2)

def write(path, text):
    # dirname('') is '' and makedirs('') raises; a bare filename is legitimate.
    os.makedirs(os.path.dirname(path) or '.', exist_ok=True)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(text)

def stanzas(text):
    return [s for s in (text or '').split('\n\n') if s.strip()]

def field(stanza, key):
    for line in stanza.split('\n'):
        if line.startswith(key + ': '):
            return line[len(key) + 2:]
    return None

# ---------------------------------------------------------------- dpkg status
def merge_status(layers, merged):
    keep, order, diverged = {}, [], []
    for name, root in layers:
        for s in stanzas(read(os.path.join(root, 'var/lib/dpkg/status'))):
            pkg = field(s, 'Package')
            if not pkg: continue
            st = (field(s, 'Status') or '').split()
            if len(st) != 3 or st[2] != 'installed':
                continue
            ver = field(s, 'Version')
            if pkg in keep:
                if keep[pkg][0] != ver:
                    diverged.append((pkg, keep[pkg][1], keep[pkg][0], name, ver))
                keep[pkg] = (ver, name, s)
            else:
                keep[pkg] = (ver, name, s); order.append(pkg)
    write(os.path.join(merged, 'var/lib/dpkg/status'),
          '\n\n'.join(keep[p][2] for p in order) + '\n')
    return len(order), diverged

# ---------------------------------------------------------------- alternatives
# Format of /var/lib/dpkg/alternatives/<group>:
#     <status>            auto | manual
#     <link>              e.g. /usr/bin/editor
#     <slave name> / <slave link>   repeating pairs
#     <blank>             ends the slave list
#     then, packed with NO separator, one record per candidate:
#     <path> / <priority> / exactly one line per slave, EMPTY when that
#     candidate provides no such slave
#     <blank>             ends the file
def parse_alt(text):
    L = text.split('\n')
    if len(L) < 2: raise ValueError('truncated alternatives file')
    status, link, i = L[0], L[1], 2
    slaves = []
    while i < len(L) and L[i] != '':
        slaves.append((L[i], L[i + 1] if i + 1 < len(L) else ''))
        i += 2
    i += 1
    alts = []
    while i < len(L) and L[i] != '':
        path, prio, i = L[i], L[i + 1] if i + 1 < len(L) else '0', i + 2
        paths = L[i:i + len(slaves)]
        paths += [''] * (len(slaves) - len(paths))
        i += len(slaves)
        alts.append((path, prio, dict(zip([s for s, _ in slaves], paths))))
    return status, link, slaves, alts

def render_alt(status, link, slaves, alts):
    out = [status, link]
    for sname, slink in slaves:
        out += [sname, slink]
    out.append('')
    for path, prio, smap in alts:
        out += [path, prio]
        out += [smap.get(sname, '') for sname, _ in slaves]
    out.append('')
    return '\n'.join(out) + '\n'

def merge_alternatives(layers, merged):
    groups, problems = {}, []
    for name, root in layers:
        d = os.path.join(root, 'var/lib/dpkg/alternatives')
        if not os.path.isdir(d): continue
        for g in sorted(os.listdir(d)):
            text = read(os.path.join(d, g))
            if text is None: continue
            try:
                status, link, slaves, alts = parse_alt(text)
            except Exception as exc:
                problems.append("%s/%s: %s" % (name, g, exc)); continue
            e = groups.setdefault(g, {'status': [], 'link': None,
                                      'slaves': [], 'alts': {}, 'from': []})
            e['status'].append(status)
            if e['link'] is None:
                e['link'] = link
            elif e['link'] != link:
                problems.append("%s: link differs (%s vs %s)" % (g, e['link'], link))
            have = {s for s, _ in e['slaves']}
            for sname, slink in slaves:
                if sname not in have:
                    e['slaves'].append((sname, slink)); have.add(sname)
            for path, prio, smap in alts:
                # PRIORITY DISAGREEMENT IS A CONFLICT, not a merge. This was
                # `e['alts'][path] = (prio, smap)` -- later layer wins, silently.
                # Reproduced 2026-09-17: a module owning ZERO paths, shipping
                # nothing but an alternatives registry entry, re-declared another
                # module's candidate at priority 1 and changed which binary
                # /usr/bin/<link> resolves to. Tier 1 ACCEPTed, tier 2 PASSed,
                # alt_bad=0. V3's invariant is "no group is short a candidate",
                # which says nothing about WHICH candidate wins. In the real
                # catalogue the exposed groups are `editor` (vim/emacs) and
                # `awk` (gawk/original-awk).
                if path in e['alts']:
                    had = e['alts'][path][0]
                    if str(had or 0) != str(prio or 0):
                        problems.append(
                            "%s: candidate %s declared at priority %s by %s and %s by %s"
                            % (g, os.path.basename(path), had,
                               '+'.join(e['from']) or '?', prio, name))
                        # Keep the HIGHER priority rather than the later layer, so
                        # a demotion cannot take effect merely by layer order.
                        if int(prio or 0) < int(had or 0):
                            continue
                e['alts'][path] = (prio, smap)
            if name not in e['from']: e['from'].append(name)

    for g, e in groups.items():
        # A composed image has no operator who chose an alternative, and the
        # symlinks are about to be recomputed by priority anyway, so 'manual'
        # is only preserved when every layer agreed on it.
        status = e['status'][0] if len(set(e['status'])) == 1 else 'auto'
        alts = sorted(e['alts'].items(),
                      key=lambda kv: (-int(kv[1][0] or 0), kv[0]))
        rendered = [(p, pr, sm) for p, (pr, sm) in alts]
        write(os.path.join(merged, 'var/lib/dpkg/alternatives', g),
              render_alt(status, e['link'], e['slaves'], rendered))
    return groups, problems

# ---------------------------------------------------------------- accounts
# passwd, group, shadow, gshadow, subuid and subgid are colon-delimited record
# files that maintainer scripts rewrite WHOLE. OverlayFS exposes only the top
# layer's copy, so in a composition every other module's accounts simply
# vanish: base+postgres+mysql shows either postgres or mysql, never both, and
# a unit declaring User=postgres then fails to resolve.
#
# Disjoint UID/GID windows (specs/uid-ranges.yaml) make the NUMBERS safe to
# union. This is what actually unions the RECORDS. The two are different
# invariants and the second was missing.
#
# key   index of the field identifying a record
# merge indices of comma-separated member lists that must be UNIONED rather
#       than overwritten -- a group can legitimately gain members from several
#       modules, e.g. ssl-cert gains postgres.
ACCOUNT_FILES = [
    ('etc/passwd',  7, 0, ()),      # name:x:uid:gid:gecos:home:shell
    ('etc/group',   4, 0, (3,)),    # name:x:gid:members
    ('etc/shadow',  9, 0, ()),      # name:hash:...
    ('etc/gshadow', 4, 0, (2, 3)),  # name:hash:admins:members
    ('etc/subuid',  3, None, ()),   # name:start:count -- whole-line union
    ('etc/subgid',  3, None, ()),
]

def merge_accounts(layers, merged):
    summary, problems = {}, []
    for rel, nfields, key_at, member_at in ACCOUNT_FILES:
        records, order, src_stat = {}, [], None
        seen_lines = []
        present = False
        for name, root in layers:
            path = os.path.join(root, rel)
            text = read(path)
            if text is None:
                continue
            present = True
            try:
                src_stat = os.stat(path)       # highest layer that has it wins
            except OSError:
                pass
            for line in text.split('\n'):
                if not line.strip():
                    continue
                if key_at is None:
                    # No stable key (subuid/subgid): union whole lines.
                    if line not in seen_lines:
                        seen_lines.append(line)
                    continue
                f = line.split(':')
                if len(f) < nfields:
                    problems.append("%s: %s malformed record %r" % (name, rel, line[:40]))
                    continue
                k = f[key_at]
                if k not in records:
                    records[k] = f; order.append(k)
                    continue
                old = records[k]
                # Same name, different number, is exactly what the UID windows
                # exist to prevent. Report rather than silently pick one.
                if rel in ('etc/passwd', 'etc/group'):
                    idx = 2
                    if old[idx] != f[idx]:
                        problems.append("%s: %s '%s' has id %s and %s"
                                        % (name, rel, k, old[idx], f[idx]))
                new = list(f)
                for mi in member_at:
                    members = [x for x in old[mi].split(',') if x]
                    for x in f[mi].split(','):
                        if x and x not in members:
                            members.append(x)
                    new[mi] = ','.join(members)
                records[k] = new
        if not present:
            continue
        out = os.path.join(merged, rel)
        if key_at is None:
            body = ''.join(l + '\n' for l in seen_lines)
            count = len(seen_lines)
        else:
            body = ''.join(':'.join(records[k]) + '\n' for k in order)
            count = len(order)
        write(out, body)
        # /etc/shadow is 0640 root:shadow. Writing it world-readable would be a
        # security regression introduced by reconciliation itself.
        if src_stat is not None:
            try:
                os.chmod(out, stat.S_IMODE(src_stat.st_mode))
                os.chown(out, src_stat.st_uid, src_stat.st_gid)
            except OSError as exc:
                problems.append("%s: cannot restore mode/owner (%s)" % (rel, exc))
        summary[rel] = count
    return summary, problems

# ---------------------------------------------------------------- diversions
# Flat file, three lines per record: original path, diverted-to path, package.
def merge_diversions(layers, merged):
    seen, out = set(), []
    for name, root in layers:
        text = read(os.path.join(root, 'var/lib/dpkg/diversions'))
        if not text: continue
        L = [l for l in text.split('\n') if l != '']
        for i in range(0, len(L) - 2, 3):
            rec = (L[i], L[i + 1], L[i + 2])
            if rec in seen: continue
            seen.add(rec); out.append(rec)
    if out:
        write(os.path.join(merged, 'var/lib/dpkg/diversions'),
              ''.join('%s\n%s\n%s\n' % r for r in out))
    return len(out)

# ---------------------------------------------------------------- extended_states
def merge_extended_states(layers, merged):
    keep, order = {}, []
    for name, root in layers:
        for s in stanzas(read(os.path.join(root, 'var/lib/apt/extended_states'))):
            key = (field(s, 'Package'), field(s, 'Architecture'))
            if key[0] is None: continue
            if key not in keep: order.append(key)
            keep[key] = s
    if order:
        write(os.path.join(merged, 'var/lib/apt/extended_states'),
              '\n\n'.join(keep[k] for k in order) + '\n')
    return len(order)

# ---------------------------------------------------------------- main
def main(argv):
    merged, groups_out, layers = None, None, []
    i = 0
    while i < len(argv):
        a = argv[i]
        if a == '--merged':      merged = argv[i + 1]; i += 2
        elif a == '--groups-out': groups_out = argv[i + 1]; i += 2
        elif '=' in a:            n, _, d = a.partition('='); layers.append((n, d)); i += 1
        else:
            sys.stderr.write("unexpected argument: %s\n" % a); return 2
    if not merged or not layers:
        sys.stderr.write(__doc__); return 2
    for n, d in layers:
        if not os.path.isdir(d):
            sys.stderr.write("layer %s: not a directory: %s\n" % (n, d)); return 2

    npkg, diverged = merge_status(layers, merged)
    print("  dpkg status        : %d packages" % npkg)
    if diverged:
        print("  version divergence : %d" % len(diverged))
        for p, m1, v1, m2, v2 in diverged[:10]:
            print("      %-28s %s=%s -> %s=%s" % (p, m1, v1, m2, v2))
    else:
        print("  version divergence : none")

    groups, problems = merge_alternatives(layers, merged)
    # Divergence was detected, printed, and then DROPPED: it never reached
    # `problems`, so this exited 0 while silently resolving a class-2 skew by
    # last-wins. Reproduced 2026-09-17 with real artefacts -- 05_check.sh
    # REJECTS curl+control-oldsnap with five skews and the whole of tier 2
    # passed. Merging one of two versions is a decision, and an unreported
    # decision is indistinguishable from no conflict.
    for pkg, m1, v1, m2, v2 in diverged:
        problems.append("class 2: %s is %s in %s and %s in %s; kept %s"
                        % (pkg, v1, m1, v2, m2, v2))
    print("  alternatives       : %d link group(s)" % len(groups))
    for g in sorted(groups):
        e = groups[g]
        if len(e['from']) > 1 or len(e['alts']) > 1:
            cands = sorted(((int(pr or 0), p) for p, (pr, _) in e['alts'].items()),
                           reverse=True)
            print("      %-12s %d candidate(s) from %s: %s"
                  % (g, len(cands), '+'.join(e['from']),
                     ', '.join("%s(%d)" % (os.path.basename(p), pr) for pr, p in cands)))
    for pr in problems:
        print("      PROBLEM %s" % pr)

    acc, acc_problems = merge_accounts(layers, merged)
    if acc:
        print("  accounts           : %s"
              % ', '.join("%s %d" % (k.split('/')[-1], v) for k, v in sorted(acc.items())))
    for pr in acc_problems:
        print("      PROBLEM %s" % pr)
    problems.extend(acc_problems)

    print("  diversions         : %d" % merge_diversions(layers, merged))
    print("  extended_states    : %d" % merge_extended_states(layers, merged))

    if groups_out:
        write(groups_out, ''.join(g + '\n' for g in sorted(groups)))
    return 2 if problems else 0

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
